GYMONE/Controllers/MonthwiseCollectionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CrystalDecisions.CrystalReports.Engine;
using GYMONE.Filters;
using GYMONE.Models;
using GYMONE.Repository;

namespace GYMONE.Controllers
{
    [MyExceptionHandler]
    [Authorize(Roles = "SystemUser,Admin")]
    public class MonthwiseCollectionController : Controller
    {
        IlReports objIlReports;

        public MonthwiseCollectionController()
        {
            objIlReports = new ReportsMaster();
        }

        [HttpGet]
        public ActionResult MonthwiseReport()
        {
            MonthwiseModel objMWlist = new MonthwiseModel();
            objMWlist.MonthNameList = BindMonth();
            return View(objMWlist);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult MonthwiseReport(FormCollection FC ,MonthwiseModel objMW)
        {
            MonthwiseModel objMWlist = new MonthwiseModel();
            objMWlist.MonthNameList = BindMonth();

            if (objMW.MonthID == "0")
            {
                ModelState.AddModelError("Message", "Please select Month");
            }
            else
            {

               
                objMWlist.MonthID = objMW.MonthID;

                DataSet ds = objIlReports.Get_MonthwisePayment_details(objMW.MonthID);
                ds.Tables[0].TableName = "RecepitDataset";

                if (ds.Tables[0].Rows.Count > 0)
                {
                    ReportClass rptH = new ReportClass();
                    rptH.FileName = Server.MapPath("~/Reports/Monthwisecollection.rpt");
                    rptH.Load();
                    rptH.SetDataSource(ds.Tables[0]);
                    Response.Buffer = false;
                    Response.ClearContent();
                    Response.ClearHeaders();

                    Stream stream = rptH.ExportToStream(CrystalDecisions.Shared.ExportFormatType.PortableDocFormat);
                    stream.Seek(0, SeekOrigin.Begin);
                    return File(stream, "application/pdf", "MonthwiseCollection.pdf");
                }

            }
        
            return View(objMWlist);
        }

        [NonAction]
        public List<SelectListItem> BindMonth()
        {
            List<SelectListItem> listofMonth = new List<SelectListItem>() { 
            new SelectListItem {Text ="Select", Value ="0" , Selected =true},
            new SelectListItem {Text ="January", Value ="1" , Selected =false},
            new SelectListItem {Text ="Febuary", Value ="2" , Selected =false},
            new SelectListItem {Text ="March", Value ="3" , Selected =false},
            new SelectListItem {Text ="April", Value ="4" , Selected =false},
            new SelectListItem {Text ="May", Value ="5" , Selected =false},
            new SelectListItem {Text ="June", Value ="6" , Selected =false},
            new SelectListItem {Text ="July", Value ="7" , Selected =false},
            new SelectListItem {Text ="August", Value ="8" , Selected =false},
            new SelectListItem {Text ="September", Value ="9" , Selected =false},
            new SelectListItem {Text ="October", Value ="10" , Selected =false},
            new SelectListItem {Text ="November", Value ="11" , Selected =false},
            new SelectListItem {Text ="December", Value ="12" , Selected =false},
            };

            return listofMonth;
        }

      
    }
}

GYMONE/Views/MonthwiseCollection/MonthwiseReport.cshtml
@model GYMONE.Models.MonthwiseModel

@{
    ViewBag.Title = "MonthwiseReport";
}

<script src="~/Scripts/jquery-1.11.1.js"></script>
<script src="~/Scripts/jquery-ui.min.js"></script>
<script src="~/bootstrap/js/bootstrap.min.js"></script>
<link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/Scripts/jquery-ui.min.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />


<div class="container">
    <div style="margin-top: 10px"></div>
    <fieldset>

        <legend class="legend">Monthwise Report</legend>

        <div class="panel">

            <div class="panel-body">

                @using (Html.BeginForm("MonthwiseReport", "MonthwiseCollection", FormMethod.Post))
                {
                    @Html.ValidationSummary()
                     @Html.AntiForgeryToken()
            
            
                    <div class="row">
                        <div class="col-md-3">
                            @Html.DisplayName("Select Month Name")
                        </div>
                        <div class="col-md-3">
                            @Html.DropDownListFor(model => model.MonthID, new SelectList(Model.MonthNameList, "Value", "Text"), new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.MonthID)
                        </div>
                        <div class="col-md-3">
                        </div>
                        <div class="col-md-3">
                        </div>

                    </div>

                    <div style="margin-top: 5px"></div>
                    <div class="row">
                        <div class="col-md-12">
                            <input id="DownloadMonthwise" class="btn btn-success" onclick="return validatepage();" type="submit" name="actionType" value="Download Monthwise" />
                        </div>
                    </div>
                    <div style="margin-top: 5px"></div>
                }
            </div>
        </div>
    </fieldset>
</div>

<script>

    function validatepage() {

        if ($("#MonthID").val() == 0) {
            alert("Please select Month to download report!");
            return false;
        }

        else {
            return true;

        }
    }

</script>