GYMONE/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GYMONE.Filters;

namespace GYMONE.Controllers
{
    
    public class DashboardController : Controller
    {
        //
        // GET: /Dashboard/
        [MyExceptionHandler]
        [Authorize(Roles = "Admin")]
        public ActionResult AdminDashboard()
        {
            return View();
        }

        [MyExceptionHandler]
        [Authorize(Roles = "SystemUser")]
        public ActionResult UserDashboard()
        {
            return View();
        }

    }
}

GYMONE/Controllers/PlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GYMONE.Filters;
using GYMONE.Models;
using GYMONE.Repository;

namespace GYMONE.Controllers
{
    
    [MyExceptionHandler]
    [Authorize(Roles = "Admin")]
    public class PlanController : Controller
    {
        IPlanMaster objIPlanMaster;
        ISchemeMaster objscheme;


        public PlanController()
        {
            objIPlanMaster = new PlanMaster();
            objscheme = new SchemeMaster();
        }

        public ActionResult Index()
        {
            return View(objIPlanMaster.GetPlan());
        }

        //
        // GET: /Plan/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Plan/Create

        [HttpGet]
        public ActionResult Create()
        {
            PlanMasterDTO objPM = new PlanMasterDTO();

            List<SchemeMasterDTO> listscheme = new List<SchemeMasterDTO>();
            listscheme = new List<SchemeMasterDTO>()
            {
            new SchemeMasterDTO { SchemeID = 0, SchemeName ="Select"}
            };



            foreach (var item in objscheme.GetSchemes())
            {
                SchemeMasterDTO sm = new SchemeMasterDTO();
                sm.SchemeID = item.SchemeID;
                sm.SchemeName = item.SchemeName;

                listscheme.Add(sm);
            }


            objPM.ListScheme = listscheme;

            objPM.ListofPeriod = new List<SelectListItem>()
            {
                new SelectListItem{ Text="Select" , Selected =true, Value ="0"  },
                new SelectListItem { Text="3 Month" , Selected =false, Value ="3"  },
                new SelectListItem { Text="6 Month" , Selected =false, Value ="6"  },
                new SelectListItem { Text="1 Year" , Selected =false, Value ="12"  },
            };


            return View(objPM);
        }

        //
        // POST: /Plan/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PlanMasterDTO objplan, FormCollection collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (objplan.SchemeID == 0)
                    {
                        ModelState.AddModelError("SchemeMessage", "Please select Scheme Name");
                        Method(objplan);
                        return View(objplan);
                    }
                    else if (objplan.PeriodID == 0)
                    {
                        ModelState.AddModelError("PeriodMessage", "Please select Period Name");
                        Method(objplan);
                        return View(objplan);
                    }
                    else
                    {


                        objplan.PlanID = 0;
                        objplan.CreateUserID = Convert.ToInt32(Session["UserID"]);

                        DateTime dt = new DateTime();
                        dt = DateTime.Now;
                        string[] date = dt.ToString("yyyy/MM/dd").Split('/');
                        int year = Convert.ToInt32(date[0]);
                        int month = Convert.ToInt32(date[1]);
                        int day = Convert.ToInt32(date[2]);

                        DateTime Newdt = new DateTime(year, month, day);
                        objplan.CreateDate = Newdt;
                        objplan.ModifyDate = Newdt;
                        objplan.RecStatus = "A";
                        TempData["notice"] = "Plan Created Successfully";
                        objIPlanMaster.InsertPlan(objplan);
                        return RedirectToAction("Create");

                    }
                }
                else
                {
                    Method(objplan);
                    return View(objplan);
                }
            }
            catch
            {
                Method(objplan);
                return View(objplan);
            }
        }

        //
        // GET: /Plan/Edit/5

        public ActionResult Edit(int id)
        {
            var Model = objIPlanMaster.GetPlanByID(Convert.ToString(id));
            EDITMethod(Model);

            return View(Model);
        }

        //
        // POST: /Plan/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PlanMasterDTO objplan, FormCollection collection, string actionType)
        {
            if (actionType == "Update")
            {

                try
                {

                    if (ModelState.IsValid)
                    {
                        if (objplan.SchemeID == 0)
                        {
                            ModelState.AddModelError("SchemeMessage", "Please select Scheme Name");
                            Method(objplan);
                            return View(objplan);
                        }
                        else if (objplan.PeriodID == 0)
                        {
                            ModelState.AddModelError("PeriodMessage", "Please select Period Name");
                            Method(objplan);
                            return View(objplan);
                        }
                        else
                        {
                            objplan.CreateUserID = Convert.ToInt32(Session["UserID"]);

                            DateTime dt = new DateTime();
                            dt = DateTime.Now;
                            string[] date = dt.ToString("yyyy/MM/dd").Split('/');
                            int year = Convert.ToInt32(date[0]);
                            int month = Convert.ToInt32(date[1]);
                            int day = Convert.ToInt32(date[2]);

                            DateTime Newdt = new DateTime(year, month, day);
                            objplan.CreateDate = Newdt;
                            objplan.ModifyDate = Newdt;
                            objplan.RecStatus = "A";

                            objIPlanMaster.UpdatePlan(objplan);
                            TempData["notice"] = "Plan Updated Successfully";

                            return RedirectToAction("Index");

                        }
                    }
                    else
                    {
                        Method(objplan);
                        return View(objplan);
                    }
                }
                catch
                {
                    return View();
                }
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        //
        // GET: /Plan/Delete/5

        public ActionResult Delete(int id)
        {
            objIPlanMaster.DeletePlan(Convert.ToString(id));
            return RedirectToAction("Index");
        }

        //
        // POST: /Plan/Delete/5



        public ActionResult PlannameExists(string Planname)
        {
            var result = objIPlanMaster.PlannameExists(Planname);
            return Json(!result, JsonRequestBehavior.AllowGet);
        }


        public void Method(PlanMasterDTO objplan)
        {
            ModelState.Remove("ListScheme");
            ModelState.Remove("ListofPeriod");
            List<SchemeMasterDTO> listscheme = new List<SchemeMasterDTO>();
            listscheme = new List<SchemeMasterDTO>() { new SchemeMasterDTO { SchemeID = 0, SchemeName = "Select" } };

            foreach (var item in objscheme.GetSchemes())
            {
                SchemeMasterDTO sm = new SchemeMasterDTO();
                sm.SchemeID = item.SchemeID;
                sm.SchemeName = item.SchemeName;
                listscheme.Add(sm);
            }


            objplan.ListScheme = listscheme;

            objplan.ListofPeriod = new List<SelectListItem>()
                {
                new SelectListItem{ Text="Select" , Selected =true, Value ="0"  },
                new SelectListItem { Text="3 Month" , Selected =false, Value ="3"  },
                new SelectListItem { Text="6 Month" , Selected =false, Value ="6"  },
                new SelectListItem { Text="1 Year" , Selected =false, Value ="12"  },
                };
        }

        public void EDITMethod(PlanMasterDTO objplan)
        {
            ModelState.Remove("ListScheme");
            ModelState.Remove("ListofPeriod");
            List<SchemeMasterDTO> listscheme = new List<SchemeMasterDTO>();
            listscheme = new List<SchemeMasterDTO>() { new SchemeMasterDTO { SchemeID = 0, SchemeName = "Select" } };

            foreach (var item in objscheme.GetSchemes())
            {
                SchemeMasterDTO sm = new SchemeMasterDTO();
                sm.SchemeID = item.SchemeID;
                sm.SchemeName = item.SchemeName;
                listscheme.Add(sm);
            }


            objplan.ListScheme = listscheme;
            objplan.SchemeID = objplan.SchemeID;

            objplan.ListofPeriod = new List<SelectListItem>()
                {
                new SelectListItem{ Text="Select" , Selected =true, Value ="0"  },
                new SelectListItem { Text="3 Month" , Selected =false, Value ="3"  },
                new SelectListItem { Text="6 Month" , Selected =false, Value ="6"  },
                new SelectListItem { Text="1 Year" , Selected =false, Value ="12"  },
                };

            objplan.PeriodID = objplan.PeriodID;
        }
    }
}

GYMONE/Controllers/SchemeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GYMONE.Filters;
using GYMONE.Models;
using GYMONE.Repository;

// INC53846 
namespace GYMONE.Controllers
{
   
    [MyExceptionHandler]
    [Authorize(Roles = "Admin")]
    public class SchemeController : Controller
    {
        ISchemeMaster objISchemeMaster;

        public SchemeController()
        {
            objISchemeMaster = new SchemeMaster();
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new SchemeMasterDTO());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SchemeMasterDTO objSchemeMasterDTO)
        {
            if (ModelState.IsValid)
            {

                objSchemeMasterDTO.Createdby = Session["UserID"].ToString();
                objISchemeMaster.InsertScheme(objSchemeMasterDTO);
                TempData["Message"] = "Scheme Create Successfully.";
                return RedirectToAction("Create");
            }
            else
            {
                ModelState.AddModelError("Error", "Please enter Scheme Name ");
            }

            ModelState.Remove("SchemeName");

            return View(objSchemeMasterDTO);
        }

        public ActionResult SchemeNameExists(string SchemeName)
        {
            var result = objISchemeMaster.SchemeNameExists(SchemeName);
            return Json(!result, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Details()
        {
            return View(objISchemeMaster.GetSchemes());
        }

        [HttpGet]
        public ActionResult Edit(string ID)
        {
            var Model = objISchemeMaster.GetSchemeByID(ID);
            return View(Model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SchemeMasterDTO objSchemeMasterDTO)
        {

            objISchemeMaster.UpdateScheme(objSchemeMasterDTO);
            TempData["MessageUpdate"] = "Scheme Updated Successfully.";
            return RedirectToAction("Details");
        }


        [HttpGet]
        public ActionResult Delete(string ID)
        {
            objISchemeMaster.DeleteScheme(ID);
            return RedirectToAction("Details");
        }
    }
}

GYMONE/Views/Dashboard/AdminDashboard.cshtml
@{
    ViewBag.Title = "Admin Dashboard";
}
<link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.11.1.js"></script>
<script src="~/bootstrap/js/bootstrap.min.js"></script>
<link href="~/Content/Site.css" rel="stylesheet" />


<div class="container">

    <div class="logo col-sm-12 text-center col-md-12 ">
        <img alt="" src="~/Images/hand.png" />
    </div>
    <div class="clearfix"></div>
    <fieldset>

        <legend>Admin Dashboard</legend>

        <div class="panel">

            <div class="panel-body">
              
                <div class="col-md-3 dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-user"></span>
                    @Html.ActionLink("Create User Account", "Register", "Account")
                </div>
                  <div class="col-md-3 dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-pencil"></span>
                    @Html.ActionLink("Create Scheme", "Create", "Scheme")
                </div>
                <div class="col-md-3 dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-pencil"></span>
                    @Html.ActionLink("Create Plan", "Create", "Plan")
                </div>


                <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-pencil"></span>
                    @Html.ActionLink("CreateRole", "RoleCreate", "Account")
                </div>
                <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-remove"></span>
                    @Html.ActionLink("DeleteRole", "DeleteRoleForUser", "Account")
                </div>
                <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-pawn"></span>
                    @Html.ActionLink("List of all roles Assigned", "DisplayAllUserroles", "Account")
                </div>
                <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-list"></span>
                    @Html.ActionLink("List of all User", "AllRegisterUserDetails", "Account")
                </div>
              


                <div class="col-md-3 dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-indent-left"></span>
                    @Html.ActionLink("List of all roles", "RoleIndex", "Account")
                </div>

                <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-random"></span>
                    @Html.ActionLink("Assign Role To User", "RoleAddToUser", "Account")
                </div>



                 <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-download-alt"></span>
                    @Html.ActionLink("Yearwise Report ", "YearwiseReport", "YearwiseCollection")
                </div>
                <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-download-alt"></span>
                    @Html.ActionLink("Monthwise Report ", "MonthwiseReport", "MonthwiseCollection")
                </div>
                <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-download-alt"></span>
                    @Html.ActionLink("Details Member Report", "DetailsMemberReport", "DetailsReport")
                </div>
                <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-list"></span>
                    @Html.ActionLink("All Member List ", "AllMemberList", "Payment")
                </div>
            </div>
        </div>
    </fieldset>

</div>

GYMONE/Views/Dashboard/UserDashboard.cshtml
@{
    ViewBag.Title = "User Dashboard";
}


<link href="~/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.11.1.js"></script>
<script src="~/bootstrap/js/bootstrap.min.js"></script>
<link href="~/Content/Site.css" rel="stylesheet" />


<div class="container">

    <div class="logo col-sm-12 text-center col-md-12 ">
        <img alt="" src="~/Images/hand.png" />
    </div>
    <div class="clearfix"></div>
    <fieldset>

        <legend>User Dashboard</legend>

        <div class="panel">

            <div class="panel-body">
               
             
                <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-user"></span>
                    @Html.ActionLink("Register Member ", "Create", "RegisterMember")
                </div>
                <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-list"></span>
                    @Html.ActionLink("Payment listing ", "PaymentDetails", "Payment")
                </div>
                <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-calendar"></span>
                    @Html.ActionLink("Payment Renewal", "RenewalDetails", "Renewal")
                </div>
                <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-download-alt"></span>
                    @Html.ActionLink("Receipt / Candidate ", "Generatereceipt", "receipt")
                </div>
                <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-download-alt"></span>
                    @Html.ActionLink("Yearwise Report ", "YearwiseReport", "YearwiseCollection")
                </div>
                <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-download-alt"></span>
                    @Html.ActionLink("Monthwise Report ", "MonthwiseReport", "MonthwiseCollection")
                </div>
                <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-download-alt"></span>
                    @Html.ActionLink("Details Member Report", "DetailsMemberReport", "DetailsReport")
                </div>
                <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-list"></span>
                    @Html.ActionLink("All Member List ", "AllMemberList", "Payment")
                </div>
                  <div class="col-md-3  dashboard-icon col-sm-3">
                    <span class="glyphicon glyphicon-calendar"></span>
                    @Html.ActionLink("Renewal Report", "RenewalReport", "RenewalSearch")
                </div>
            </div>
        </div>
    </fieldset>

</div>